spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cricketboard
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    connect-retries: 10
  jpa.properties:
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true