CREATE TABLE bowl (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   match_id INTEGER NOT NULL,
   innings_id INTEGER NOT NULL,
   over_number INTEGER NOT NULL,
   ball_number INTEGER NOT NULL,
   ball_type VARCHAR(50) NOT NULL,
   bowler_id INTEGER NOT NULL,
   ball_speed DOUBLE PRECISION NOT NULL,
   striker_batter_id INTEGER NOT NULL,
   non_striker_batter_id INTEGER,
   run INTEGER,
   run_type VARCHAR(50),
   front_umpire_id INTEGER,
   leg_umpire_id INTEGER,
   wicket_id INTEGER,
   time_stamp TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT pk_bowl PRIMARY KEY (id)
);