CREATE TABLE "activity" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "match_id" integer not null,
  "innings_id" integer not null,
  "start_time" timestamp,
  "end_time" timestamp,
  "activity_type" varchar(100) not null,
  "activity_details" json
);